// ─────────────────────────────────────────────────────────
// Intermediate Representation (IR) Types
// Language-neutral artifacts extracted from .NET source code.
// Target platform plugins consume these to generate platform-specific code.
// ─────────────────────────────────────────────────────────

// ── Top-Level Union ──

export type IRArtifact =
  | IRController
  | IRModel
  | IRService
  | IRRepository
  | IRMiddleware
  | IRConfig
  | IRAuth
  | IRRoute
  | IRValidationSchema
  | IRDiRegistration
  | IRDomainEvent
  | IRValueObject
  | IREnum
  | IRMapper
  | IRUseCaseOrHandler
  | IRSignalRHub
  | IRBackgroundJob
  | IRCacheUsage
  | IRLoggingConfig
  | IRHealthCheck
  | IRCorsConfig
  | IRApiVersioning
  | IRSwaggerConfig
  | IRRateLimiting
  | IRStoredProcedure
  | IRDbMigration
  | IRNuGetMapping
  | IRRazorView;

// ── Shared Primitives ──

export interface IRTypeRef {
  name: string;
  isArray: boolean;
  isOptional: boolean;
  isNullable: boolean;
  genericArgs?: IRTypeRef[];
  sourceType: string;
}

export interface IRParameter {
  name: string;
  type: IRTypeRef;
  source: 'body' | 'query' | 'path' | 'header' | 'cookie' | 'form' | 'injected';
  defaultValue?: string;
  validationRules: IRValidationRule[];
}

export interface IRValidationRule {
  kind:
    | 'required'
    | 'min-length'
    | 'max-length'
    | 'range'
    | 'email'
    | 'regex'
    | 'url'
    | 'phone'
    | 'compare'
    | 'custom';
  params: Record<string, unknown>;
  errorMessage?: string;
}

export interface IRProperty {
  name: string;
  type: IRTypeRef;
  accessModifier: 'public' | 'private' | 'protected' | 'internal';
  isReadonly: boolean;
  isStatic: boolean;
  isVirtual: boolean;
  defaultValue?: string;
  annotations: IRAnnotation[];
}

export interface IRAnnotation {
  name: string;
  arguments: Record<string, unknown>;
}

export interface IRDependency {
  interfaceName: string;
  implementationName?: string;
  logicalRole:
    | 'repository'
    | 'service'
    | 'domain-service'
    | 'bus'
    | 'external'
    | 'config'
    | 'logger'
    | 'cache';
}

export interface IRMethod {
  name: string;
  parameters: IRParameter[];
  returnType: IRTypeRef;
  isAsync: boolean;
  isStatic: boolean;
  accessModifier: 'public' | 'private' | 'protected' | 'internal';
  body?: IRMethodBody;
}

export interface IRMethodBody {
  queryOperations: IRQueryOperation[];
  businessRules: string[];
  rawSourceLines: string[];
}

export interface IRQueryOperation {
  kind:
    | 'find-one'
    | 'find-many'
    | 'create'
    | 'update'
    | 'delete'
    | 'count'
    | 'exists'
    | 'raw';
  entity: string;
  filters?: Record<string, unknown>;
  includes?: string[];
  orderBy?: { field: string; direction: 'asc' | 'desc' }[];
  skip?: number;
  take?: number;
  rawSql?: string;
}

// ── Controller IR ──

export interface IRController {
  kind: 'controller';
  name: string;
  basePath: string;
  boundedContext?: string;
  dependencies: IRDependency[];
  actions: IRAction[];
  sourceFile: string;
}

export interface IRAction {
  name: string;
  httpMethod: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  path: string;
  parameters: IRParameter[];
  returnType: IRTypeRef;
  responseMap: IRResponseMapping[];
  authRequired: boolean;
  authRoles?: string[];
  authPolicies?: string[];
  isAsync: boolean;
  description?: string;
}

export interface IRResponseMapping {
  statusCode: number;
  condition:
    | 'success'
    | 'created'
    | 'no-content'
    | 'not-found'
    | 'bad-request'
    | 'unauthorized'
    | 'forbidden'
    | 'conflict'
    | 'error';
  bodyType?: IRTypeRef;
}

// ── Model / Entity IR ──

export interface IRModel {
  kind: 'model';
  name: string;
  boundedContext?: string;
  role: 'entity' | 'aggregate-root' | 'dto' | 'view-model';
  properties: IRProperty[];
  relationships: IRRelationship[];
  tableMapping?: IRTableMapping;
  behaviors: IRMethod[];
  sourceFile: string;
}

export interface IRRelationship {
  type: 'one-to-many' | 'many-to-one' | 'one-to-one' | 'many-to-many';
  targetEntity: string;
  foreignKey?: string;
  navigationProperty: string;
  isRequired: boolean;
  cascadeDelete?: boolean;
}

export interface IRTableMapping {
  tableName: string;
  schema?: string;
  columns: IRColumnMapping[];
  indexes: IRIndexDef[];
}

export interface IRColumnMapping {
  propertyName: string;
  columnName: string;
  columnType?: string;
  isPrimaryKey: boolean;
  isAutoGenerated: boolean;
  maxLength?: number;
  isUnique: boolean;
  isNullable: boolean;
}

export interface IRIndexDef {
  columns: string[];
  isUnique: boolean;
  name?: string;
}

// ── Service / Use Case / Handler IR ──

export interface IRService {
  kind: 'service';
  name: string;
  boundedContext?: string;
  role: 'application-service' | 'domain-service';
  interfaceName?: string;
  dependencies: IRDependency[];
  methods: IRMethod[];
  sourceFile: string;
}

export interface IRUseCaseOrHandler {
  kind: 'use-case-or-handler';
  name: string;
  cqrsType: 'command' | 'query';
  inputType: IRTypeRef;
  outputType: IRTypeRef;
  dependencies: IRDependency[];
  boundedContext?: string;
  sourceMethod: string;
}

// ── Repository IR ──

export interface IRRepository {
  kind: 'repository';
  name: string;
  interfaceName?: string;
  entity: string;
  boundedContext?: string;
  methods: IRMethod[];
  sourceFile: string;
}

// ── Value Object IR ──

export interface IRValueObject {
  kind: 'value-object';
  name: string;
  boundedContext?: string;
  properties: IRProperty[];
  validationRules: IRValidationRule[];
  sourceFile: string;
}

// ── Enum IR ──

export interface IREnum {
  kind: 'enum';
  name: string;
  boundedContext?: string;
  members: { name: string; value?: number | string }[];
  sourceFile: string;
}

// ── Middleware IR ──

export interface IRMiddleware {
  kind: 'middleware';
  name: string;
  scope: 'global' | 'route' | 'controller';
  order: number;
  type: 'action-filter' | 'exception-filter' | 'authorization-filter' | 'http-module' | 'pipeline';
  configuration: Record<string, unknown>;
  sourceFile: string;
}

// ── Config IR ──

export interface IRConfig {
  kind: 'config';
  entries: IRConfigEntry[];
  connectionStrings: IRConnectionString[];
  sourceFile: string;
}

export interface IRConfigEntry {
  key: string;
  value: string;
  section: string;
  isSecret: boolean;
}

export interface IRConnectionString {
  name: string;
  connectionString: string;
  provider: string;
}

// ── Auth IR ──

export interface IRAuth {
  kind: 'auth';
  schemes: IRAuthScheme[];
  policies: IRAuthPolicy[];
  sourceFile: string;
}

export interface IRAuthScheme {
  type: 'jwt' | 'cookie' | 'basic' | 'oauth2' | 'api-key' | 'forms' | 'identity';
  configuration: Record<string, unknown>;
}

export interface IRAuthPolicy {
  name: string;
  roles?: string[];
  claims?: Record<string, string>;
}

// ── Route IR ──

export interface IRRoute {
  kind: 'route';
  controllerName: string;
  basePath: string;
  boundedContext?: string;
  actions: {
    httpMethod: string;
    path: string;
    handlerName: string;
    authRequired: boolean;
    authRoles?: string[];
  }[];
}

// ── Validation Schema IR ──

export interface IRValidationSchema {
  kind: 'validation-schema';
  name: string;
  targetType: string;
  boundedContext?: string;
  fields: {
    name: string;
    type: IRTypeRef;
    rules: IRValidationRule[];
  }[];
  sourceFile: string;
}

// ── DI Registration IR ──

export interface IRDiRegistration {
  kind: 'di-registration';
  registrations: {
    interfaceName: string;
    implementationName: string;
    lifetime: 'singleton' | 'scoped' | 'transient';
    boundedContext?: string;
  }[];
  sourceFile: string;
}

// ── Domain Event IR ──

export interface IRDomainEvent {
  kind: 'domain-event';
  name: string;
  boundedContext?: string;
  properties: IRProperty[];
  sourceFile: string;
}

// ── Mapper IR ──

export interface IRMapper {
  kind: 'mapper';
  name: string;
  sourceType: string;
  targetType: string;
  boundedContext?: string;
  mappings: { from: string; to: string; transform?: string }[];
  sourceFile: string;
}

// ── Cross-Cutting Concern IRs ──

export interface IRSignalRHub {
  kind: 'signalr-hub';
  name: string;
  hubPath: string;
  methods: IRMethod[];
  events: { name: string; payloadType: IRTypeRef }[];
  groups: string[];
  sourceFile: string;
}

export interface IRBackgroundJob {
  kind: 'background-job';
  name: string;
  schedule?: string;
  type: 'hosted-service' | 'hangfire' | 'quartz' | 'timer';
  method: IRMethod;
  dependencies: IRDependency[];
  sourceFile: string;
}

export interface IRCacheUsage {
  kind: 'cache-usage';
  type: 'memory' | 'distributed' | 'redis';
  operations: { method: string; key: string; ttl?: number }[];
  sourceFile: string;
}

export interface IRLoggingConfig {
  kind: 'logging-config';
  provider: 'ilogger' | 'serilog' | 'nlog' | 'log4net';
  sinks: string[];
  logLevel: string;
  structuredLogging: boolean;
  sourceFile: string;
}

export interface IRHealthCheck {
  kind: 'health-check';
  name: string;
  endpoint: string;
  checks: { name: string; type: 'db' | 'redis' | 'external' | 'custom' }[];
  sourceFile: string;
}

export interface IRCorsConfig {
  kind: 'cors-config';
  origins: string[];
  methods: string[];
  headers: string[];
  allowCredentials: boolean;
  sourceFile: string;
}

export interface IRApiVersioning {
  kind: 'api-versioning';
  strategy: 'url' | 'header' | 'query';
  versions: string[];
  defaultVersion: string;
  sourceFile: string;
}

export interface IRSwaggerConfig {
  kind: 'swagger-config';
  title: string;
  version: string;
  description?: string;
  endpoints: {
    path: string;
    method: string;
    summary?: string;
    tags?: string[];
  }[];
  uiProvider: 'swagger-ui' | 'scalar' | 'both' | 'none';
  sourceFile: string;
}

export interface IRRateLimiting {
  kind: 'rate-limiting';
  policies: {
    name: string;
    limit: number;
    window: string;
    appliesTo?: string[];
  }[];
  sourceFile: string;
}

export interface IRStoredProcedure {
  kind: 'stored-procedure';
  name: string;
  parameters: IRParameter[];
  returnType: IRTypeRef;
  rawSql?: string;
  sourceFile: string;
}

export interface IRDbMigration {
  kind: 'db-migration';
  name: string;
  timestamp: string;
  upOperations: string[];
  downOperations: string[];
  seedData?: Record<string, unknown[]>;
  sourceFile: string;
}

export interface IRNuGetMapping {
  kind: 'nuget-mapping';
  nugetPackage: string;
  nugetVersion: string;
  targetEquivalent: string | null;
  targetVersion?: string;
  notes?: string;
}

export interface IRRazorView {
  kind: 'razor-view';
  name: string;
  path: string;
  model?: string;
  layout?: string;
  status: 'unmigrated';
}
